
import 'package:flutter/material.dart';


class CustomSearchDelegate extends SearchDelegate {

  // late List<List<dynamic>> _data = [];
  List<String> searchTerms = ["city",
    "Tokyo",
    "Jakarta",
    "Delhi",
    "Manila",
    "São Paulo",
    "Seoul",
    "Mumbai",
    "Shanghai",
    "Mexico City",
    "Guangzhou",
    "Cairo",
    "Beijing",
    "New York",
    "Kolk?ta",
    "Moscow",
    "Bangkok",
    "Dhaka",
    "Buenos Aires",
    "?saka",
    "Lagos",
    "Istanbul",
    "Karachi",
    "Kinshasa",
    "Shenzhen",
    "Bangalore",
    "Ho Chi Minh City",
    "Tehran",
    "Los Angeles",
    "Rio de Janeiro",
    "Chengdu",
    "Baoding",
    "Chennai",
    "Lahore",
    "London",
    "Paris",
    "Tianjin",
    "Linyi",
    "Shijiazhuang",
    "Zhengzhou",
    "Nanyang",
    "Hyder?b?d",
    "Wuhan",
    "Handan",
    "Nagoya",
    "Weifang",
    "Lima",
    "Zhoukou",
    "Luanda",
    "Ganzhou",
    "Tongshan",
    "Kuala Lumpur",
    "Chicago",
    "Heze",
    "Chongqing",
    "Hanoi",
    "Fuyang",
    "Changsha",
    "Dongguan",
    "Jining",
    "Jinan",
    "Pune",
    "Foshan",
    "Bogotá",
    "Ahmedabad",
    "Nanjing",
    "Changchun",
    "Tangshan",
    "Cangzhou",
    "Dar es Salaam",
    "Hefei",
    "Hong Kong",
    "Shaoyang",
    "Zhanjiang",
    "Shangqiu",
    "Nantong",
    "Yancheng",
    "Nanning",
    "Hengyang",
    "Zhumadian",
    "Shenyang",
    "Xingtai",
    "Xi’an",
    "Santiago",
    "Yantai",
    "Riyadh",
    "Luoyang",
    "Kunming",
    "Shangrao",
    "Hangzhou",
    "Bijie",
    "Quanzhou",
    "Miami",
    "Wuxi",
    "Huanggang",
    "Maoming",
    "Nanchong",
    "Zunyi",
    "Qujing",
    "Baghdad",
    "Xinyang",
    "Jieyang",
    "Khartoum",
    "Madrid",
    "Allah?b?d",
    "Yulin",
    "Changde",
    "Liaocheng",
    "Qingdao",
    "Dallas",
    "Nangandao",
    "Xiangyang",
    "Philadelphia",
    "Giza",
    "Lu’an",
    "Zhaotong",
    "Yichun",
    "Dezhou",
    "Nairobi",
    "Nanchang",
    "Tai’an",
    "Dazhou",
    "Houston",
    "Guadalajara",
    "Yongzhou",
    "Atlanta",
    "Rangoon",
    "Toronto",
    "Suihua",
    "Saint Petersburg",
    "Washington",
    "Qiqihar",
    "Suzhou",
    "Shantou",
    "Weinan",
    "Changzhou",
    "Singapore",
    "Fuzhou",
    "Pudong",
    "Belo Horizonte",
    "Zhangzhou",
    "Yuncheng",
    "Suzhou",
    "Xianyang",
    "Guilin",
    "Taizhou",
    "Abidjan",
    "Huaihua",
    "Ji’an",
    "Xiaoganzhan",
    "Pingdingshan",
    "Jiujiang",
    "S?rat",
    "Guiyang",
    "Alexandria",
    "Bozhou",
    "Sydney",
    "Huizhou",
    "Huai’an",
    "Chenzhou",
    "Barcelona",
    "Anqing",
    "Suqian",
    "Boston",
    "Jiangmen",
    "Mianyang",
    "Harbin",
    "Huanglongsi",
    "Melbourne",
    "Zibo",
    "Dalian",
    "Hengshui",
    "Yibin",
    "Yangzhou",
    "Timbío",
    "Johannesburg",
    "Yiyang",
    "Guigang",
    "Xinpu",
    "Meizhou",
    "Casablanca",
    "Langfang",
    "Zhangjiakou",
    "Chifeng",
    "Linfen",
    "Jiangguanchi",
    "Kabul",
    "Phoenix",
    "Luzhou",
    "Taiyuan",
    "Zhaoqing",
    "Xiaoxita",
    "Xiamen",
    "Fuzhou",
    "Liuzhou",
    "Zhuzhou",
    "Amman",
    "Jeddah",
    "Chuzhou",
    "Loudi",
    "Deyang",
    "Qingyuan",
    "Kano",
    "Wuhu",
    "Seattle",
    "Yokohama",
    "Binzhou",
    "Baojishi",
    "Zaozhuang",
    "Neijiang",
    "Baicheng",
    "Berlin",
    "Anshan",
    "Lanzhou",
    "Puyang",
    "San Francisco",
    "Jiaozuo",
    "Hechi",
    "Montréal",
    "Detroit",
    "Chengde",
    "Busan",
    "Algiers",
    "Hanzhong",
    "Shiyan",
    "Lucknow",
    "Siping",
    "Yulinshi",
    "Changzhi",
    "Qinzhou",
    "Bazhou",
    "Qincheng",
    "Zhongshan",
    "Suining",
    "Leshan",
    "San Diego",
    "Faisalabad",
    "Guang’an",
    "Tongren",
    "Bengbu",
    "Santa Cruz",
    "Qinhuangdao",
    "Tongliao",
    "Jinzhou",
    "Zhenjiang",
    "Ürümqi",
    "Heyuan",
    "Jaipur",
    "Xinzhou",
    "Wuzhou",
    "Addis Ababa",
    "Chaoyang",
    "Brasília",
    "Mashhad",
    "Shaoguan",
    "Kuwait City",
    "Shanwei",
    "Quezon City",
    "Minneapolis",
    "Kyiv",
    "Sanaa",
    "Meishan",
    "Guatemala City",
    "Incheon",
    "Ningde",
    "Tampa",
    "Daqing",
    "Putian",
    "Bandung",
    "Surabaya",
    "Salvador",
    "Denver",
    "Rome",
    "La Paz",
    "Hohhot",
    "Xiangtan",
    "Pyongyang",
    "Taichung",
    "Weihai",
    "Rizhao",
    "Mudanjiang",
    "Kaohsiung",
    "Guayaquil",
    "Tieling",
    "Cawnpore",
    "Dingxi",
    "Taipei",
    "Nanping",
    "Zigong",
    "Chaozhou",
    "Baotou",
    "Gulou",
    "Longyan",
    "Ankang",
    "Baoshan",
    "Huludao",
    "Antananarivo",
    "Yanjiang",
    "Chattogram",
    "Santo Domingo",
    "Sanming",
    "Longba",
    "Brooklyn",
    "Yangjiang",
    "Jiamusi",
    "Ibadan",
    "Luohe",
    "Lincang",
    "Medellín",
    "Xuanzhou",
    "Yunfu",
    "Dubai",
    "Mirz?pur",
    "Tashkent",
    "Guangyuan",
    "Cali",
    "Huangshi",
    "Ouagadougou",
    "Daegu",
    "Fortaleza",
    "Yaoundé",
    "Douala",
    "Jilin",
    "Dandong",
    "Lianshan",
    "Yingkou",
    "N?gpur",
    "Omdurman",
    "Bekasi",
    "Gh?zi?b?d",
    "Yuxi",
    "Brisbane",
    "Anshun",
    "Depok",
    "Shangzhou",
    "Huainan",
    "Kuaidamao",
    "Accra",
    "Fukuoka",
    "Jincheng",
    "Vancouver",
    "Tangerang",
    "Sanmenxia",
    "Laibin",
    "Queens",
    "Qinbaling",
    "Xining",
    "Ma’anshan",
    "Yan’an",
    "Baku",
    "Gaoping",
    "Harare",
    "Havana",
    "Phnom Penh",
    "Ningbo",
    "Mogadishu",
    "Puning",
    "Medan",
    "Huaibei",
    "Qingyang",
    "Riverside",
    "Baltimore",
    "Haiphong",
    "Las Vegas",
    "Chongzuo",
    "Rawalpindi",
    "Kumasi",
    "Portland",
    "Vadodara",
    "Hezhou",
    "Pingliang",
    "San Antonio",
    "Perth",
    "Vish?khapatnam",
    "Shengli",
    "Gujranwala",
    "Baicheng",
    "Fushun",
    "St. Louis",
    "Bamako",
    "Quito",
    "Minsk",
    "Indore",
    "Yinchuan",
    "Kananga",
    "Peshawar",
    "Sapporo",
    "E?fah?n",
    "Caracas",
    "Pingxiang",
    "Aleppo",
    "Tijuana",
    "Almaty",
    "Vienna",
    "Th?ne",
    "Sacramento",
    "Blantyre",
    "Tainan",
    "Zhuhai",
    "Bucharest",
    "Curitiba",
    "Multan",
    "Xiping",
    "Ecatepec",
    "Jixi",
    "Saidu Sharif",
    "Liaoyang",
    "Hamburg",
    "Meru",
    "Brazzaville",
    "Orlando",
    "Fuxin",
    "Wuwei",
    "Manaus",
    "Bhop?l",
    "San Jose",
    "Warsaw",
    "Lubumbashi",
    "Davao",
    "Haikou",
    "Damascus",
    "Shuyangzha",
    "Brussels",
    "Lusaka",
    "Hyderabad City",
    "Budapest",
    "Shuozhou",
    "Cleveland",
    "Benxi",
    "Baiyin",
    "Pittsburgh",
    "Patna",
    "Mosul",
    "Caloocan City",
    "Austin",
    "Sanzhou",
    "Beihai",
    "Mecca",
    "Heihe",
    "Jingdezhen",
    "Conakry",
    "Kampala",
    "Cincinnati",
    "Recife",
    "Yushan",
    "Zhongli",
    "Kansas City",
    "Manhattan",
    "Bil?spur",
    "Semarang",
    "Ludhi?na",
    "Novosibirsk",
    "Chengtangcun",
    "?gra",
    "Karaj",
    "Wenzhou",
    "Indianapolis",
    "León de los Aldama",
    "Puebla",
    "Kaly?n",
    "Madurai",
    "Mbuji-Mayi",
    "Hebi",
    "Sh?r?z",
    "Jamshedpur",
    "Columbus",
    "Tabr?z",
    "Maracaibo",
    "Kawasaki",
    "Aba",
    "Palembang",
    "Zhangjiajie",
    "K?be",
    "Charlotte",
    "Changshu",
    "Lianjiang",
    "Ximeicun",
    "Jianguang",
    "Yucheng",
    "Belém",
    "Guiping",
    "Leizhou",
    "Gwangju",
    "Munich",
    "N?sik",
    "Porto Alegre",
    "Valencia",
    "Onitsha",
    "Abu Dhabi",
    "Virginia Beach",
    "Daejeon",
    "Zapopan",
    "Yekaterinburg",
    "Huazhou",
    "Ky?to",
    "Shuangyashan",
    "Pizhou",
    "El Kelaa des Srarhna",
    "Kharkiv",
    "Yangshe",
    "Guyuan",
    "Khulna",
    "Muscat",
    "Bronx",
    "Gaozhou",
    "Chizhou",
    "Far?d?b?d",
    "Ulaanbaatar",
    "Goiânia",
    "Fuqing",
    "Belgrade",
    "Pingdu",
    "Milan",
    "Aurang?b?d",
    "Yutan",
    "Milwaukee",
    "Huangshan",
    "Auckland",
    "Makassar",
    "Santiago",
    "Prague",
    "R?jkot",
    "Liangshi",
    "Córdoba",
    "Guarulhos",
    "Al Ba?rah",
    "Saitama",
    "Juárez",
    "Montevideo",
    "Xintai",
    "Wusong",
    "Meerut",
    "Yushu",
    "Rongcheng",
    "Huazhou",
    "Yangquan",
    "Adelaide",
    "Baishan",
    "Dayan",
    "Haicheng",
    "Jiangyin",
    "Huaiyin",
    "Wuzhong",
    "Cacuaco",
    "Barranquilla",
    "Sofia",
    "Soweto",
    "Jabalpur",
    "Rucheng",
    "Nizhniy Novgorod",
    "Shaoyang",
    "Dhanb?d",
    "Comayagüela",
    "Laiwu",
    "Sharjah",
    "Jingling",
    "Kazan",
    "Suwon",
    "Yongcheng",
    "Calgary",
    "C?n Th?",
    "Abuja",
    "Mandalay",
    "Beidao",
    "Xiangshui",
    "Dadukou",
    "Vila Velha",
    "Chelyabinsk",
    "Mombasa",
    "Providence",
    "V?r?nasi",
    "Qom",
    "Zhangye",
    "Hiroshima",
    "Maiduguri",
    "Maputo",
    "Doha",
    "Rosario",
    "Pikine",
    "Xinyu",
    "Ahv?z",
    "Jacksonville",
    "Medina",
    "Sr?nagar",
    "Omsk",
    "Liaoyuan",
    "Cilacap",
    "Yingtan",
    "Bandar Lampung",
    "Samara",
    "Guankou",
    "Ulsan",
    "Dingzhou",
    "Campinas",
    "Lianyuan",
    "Dakar",
    "Rongcheng",
    "Kaiyuan",
    "Nay Pyi Taw",
    "Kigali",
    "Leiyang",
    "Yichun",
    "Benin City",
    "Birmingham",
    "Xiantao",
    "Amritsar",
    "Callao",
    "Monterrey",
    "Al?garh",
    "Yingchuan",
    "Ciudad Nezahualcóyotl",
    "Tripoli",
    "Nampo",
    "Rostov",
    "Tegucigalpa",
    "Tbilisi",
    "Guw?h?ti",
    "Ufa",
    "Fès",
    "Biên Hòa",
    "N’Djamena",
    "Ikare",
    "Salt Lake City",
    "Bhilai",
    "H?ora",
    "Tamale",
    "Xibeijie",
    "Copenhagen",
    "Nezahualcóyotl",
    "Hanchuan",
    "Gongzhuling",
    "Krasnoyarsk",
    "Cologne",
    "Yicheng",
    "Zhufeng",
    "São Gonçalo",
    "Nashville",
    "Yerevan",
    "Nur-Sultan",
    "Nouakchott",
    "Vereeniging",
    "Richmond",
    "São Luís",
    "R?nchi",
    "San Pedro Sula",
    "Taixing",
    "Gwalior",
    "Memphis",
    "Goyang",
    "Bezw?da",
    "Edmonton",
    "Bishkek",
    "Mizhou",
    "Tunis",
    "Xishan",
    "Ezhou",
    "Barquisimeto",
    "Sendai",
    "Hegang",
    "Kathmandu",
    "Mexicali",
    "Voronezh",
    "Perm",
    "Changwon",
    "Zhongwei",
    "Shouguang",
    "Bogor",
    "Raleigh",
    "Cartagena",
    "Chand?garh",
    "Matola",
    "Jodhpur",
    "Ogbomoso",
    "Shymkent",
    "Niamey",
    "Taizhou",
    "Managua",
    "Bagam",
    "Shubr? al Khaymah",
    "Maceió",
    "Monrovia",
    "Wafangdian",
    "Zhongxiang",
    "Odesa",
    "Port-au-Prince",
    "New Orleans",
    "Villahermosa",
    "Th? ??c",
    "Volgograd",
    "Mysore",
    "Islamabad",
    "Xinyi",
    "Raipur",
    "Arequipa",
    "Port Harcourt",
    "Louisville",
    "Zaoyang",
    "Shuizhai",
    "Xingyi",
    "Kota",
    "Quetta",
    "Ottawa",
    "Stockholm",
    "Asmara",
    "Freetown",
    "Vientiane",
    "Jerusalem",
    "Bangui",
    "Panama City",
    "Amsterdam",
    "Lomé",
    "Libreville",
    "Zagreb",
    "Dushanbe",
    "Lilongwe",
    "Cotonou",
    "Colombo",
    "Pretoria",
    "Winnipeg",
    "Quebec City",
    "Oslo",
    "Athens",
    "Bujumbura",
    "Helsinki",
    "Skopje",
    "Chisinau",
    "Riga",
    "Kingston",
    "Rabat",
    "Vilnius",
    "San Salvador",
    "Djibouti",
    "Dublin",
    "The Hague",
    "Asunción",
    "Lisbon",
    "Bratislava",
    "Kitchener",
    "Tallinn",
    "Beirut",
    "Cape Town",
    "Tirana",
    "Wellington",
    "Dodoma",
    "Halifax",
    "Bissau",
    "Canberra",
    "Juba",
    "Yamoussoukro",
    "Victoria",
    "Maseru",
    "Nicosia",
    "Windhoek",
    "Port Moresby",
    "Porto-Novo",
    "Sucre",
    "San José",
    "Ljubljana",
    "Sarajevo",
    "Nassau",
    "Bloemfontein",
    "Fort-de-France",
    "New Delhi",
    "Gaborone",
    "Paramaribo",
    "Dili",
    "Male",
    "Georgetown",
    "Gibraltar",
    "Saint-Denis",
    "Malabo",
    "Podgorica",
    "Manama",
    "Port Louis",
    "Willemstad",
    "Bern",
    "Papeete",
    "Luxembourg",
    "Reykjavík",
    "Praia",
    "Sri Jayewardenepura Kotte",
    "Bridgetown",
    "Moroni",
    "Thimphu",
    "Mbabane",
    "Nouméa",
    "Honiara",
    "Suva",
    "Ankara",
    "Castries",
    "Cayenne",
    "São Tomé",
    "Port-Vila",
    "Hamilton",
    "Bandar Seri Begawan",
    "Monaco",
    "Gitega",
    "Port of Spain",
    "Apia",
    "Tarawa",
    "Oranjestad",
    "Saint Helier",
    "Banjul",
    "Mamoudzou",
    "Majuro",
    "Douglas",
    "George Town",
    "Victoria",
    "Kingstown",
    "Andorra la Vella",
    "Saint John’s",
    "Nuku‘alofa",
    "Ashgabat",
    "Nuuk",
    "Belmopan",
    "Roseau",
    "Basseterre",
    "Tórshavn",
    "Pago Pago",
    "Valletta",
    "Gaza",
    "Grand Turk",
    "Palikir",
    "Funafuti",
    "Vaduz",
    "Lobamba",
    "Avarua",
    "Saint George’s",
    "San Marino",
    "Al Quds",
    "Capitol Hill",
    "Stanley",
    "Vatican City",
    "Alofi",
    "Basse-Terre",
    "Hagåtña",
    "Marigot",
    "Jamestown",
    "Brades",
    "Philipsburg",
    "Yaren",
    "Pristina",
    "Gustavia",
    "Road Town",
    "Ngerulmud",
    "Saint-Pierre",
    "The Valley",
    "Mata-Utu",
    "Kingston",
    "Longyearbyen",
    "Tifariti",
    "Adamstown",
    "Flying Fish Cove",
    "King Edward Point",
    "Bareilly",
    "Qu?ng Hà",
    "Xingcheng",
    "Dongtai",
    "Al Man??rah",
    "Yingcheng",
    "Chiba",
    "Pekanbaru",
    "Luocheng",
    "Dnipro",
    "Danyang",
    "Natal",
    "Nada",
    "Zamboanga City",
    "Kirkuk",
    "Naples",
    "Wuchuan",
    "Huilong",
    "Oklahoma City",
    "Morelia",
    "Cebu City",
    "Shaoxing",
    "Coimbatore",
    "Santo Domingo Este",
    "Setagaya",
    "S?ngnam",
    "Taishan",
    "Fangchenggang",
    "Sol?pur",
    "Tangier",
    "Anqiu",
    "Feicheng",
    "Kerm?nsh?h",
    "Kitaky?sh?",
    "Meishan",
    "Khartoum North",
    "Kisangani",
    "Aguascalientes",
    "Marrakech",
    "Donetsk",
    "Trujillo",
    "Taihe",
    "Bridgeport",
    "Trichinopoly",
    "Xin’an",
    "Taihecun",
    "Naucalpan de Juárez",
    "Owerri",
    "Padang",
    "Qingzhou",
    "Buffalo",
    "Lichuan",
    "Daye",
    "Fort Worth",
    "Hengzhou",
    "Campo Grande",
    "Zhuanghe",
    "Hartford",
    "Bobo-Dioulasso",
    "Ad Damm?m",
    "Lhasa",
    "Jiaozhou",
    "Taguig City",
    "Mérida",
    "Yangchun",
    "Bucheon",
    "Dengtalu",
    "Antipolo",
    "Hubli",
    "Abeokuta",
    "Cancún",
    "Tucson",
    "Krasnodar",
    "Natal",
    "Chihuahua",
    "Klang",
    "Turin",
    "Ar Ram?d?",
    "Laiyang",
    "Sale",
    "Jalandhar",
    "Kaifeng Chengguanzhen",
    "Ikeja",
    "Malang",
    "Marseille",
    "Saltillo",
    "Gaomi",
    "Ipoh",
    "Hai’an",
    "Oran",
    "Hermosillo",
    "Weichanglu",
    "Shache",
    "Leping",
    "Hailun",
    "Macheng",
    "Akure",
    "Ilorin",
    "Teresina",
    "Yuci",
    "Omaha",
    "Saratov",
    "Erbil",
    "Iguaçu",
    "El Paso",
    "Pasig City",
    "Denpasar",
    "Dehui",
    "Bhubaneshwar",
    "Tongchuan",
    "Cheongju",
    "Warri",
    "Pointe-Noire",
    "Sakai",
    "Rongjiawan",
    "Butterworth",
    "Renqiu",
    "Honolulu",
    "Xindi",
    "Wu’an",
    "São Bernardo do Campo",
    "Gaoyou",
    "Culiacán",
    "Hejian",
    "Yiyang",
    "Puxi",
    "Zijinglu",
    "João Pessoa",
    "McAllen",
    "Querétaro",
    "Abaeté",
    "Palermo",
    "Qingping",
    "Valencia",
    "Niigata",
    "Leeds",
    "Mor?d?b?d",
    "Hamamatsu",
    "Xiangxiang",
    "Chaohucun",
    "Fuyang",
    "Homs",
    "Lubango",
    "San Luis Potosí",
    "Cencheng",
    "Dali",
    "Hamh?ng",
    "Kraków",
    "Hempstead",
    "Frankfurt",
    "Al ‘Ayn",
    "Songzi",
    "Laixi",
    "Bahawalpur",
    "Zhongba",
    "Kaduna",
    "Qingnian",
    "Albuquerque",
    "Xinhualu",
    "Nerima",
    "Guangshui",
    "Tlajomulco de Zúñiga",
    "Samarinda",
    "Pietermaritzburg",
    "Changhua",
    "Kolh?pur",
    "Sizhan",
    "Ciudad Guayana",
    "Cúcuta",
    "Licheng",
    "?ta-ku",
    "Thiruvananthapuram",
    "Tyumen",
    "Nampula",
    "Zaporizhzhia",
    "Chengguan",
    "Kumamoto",
    "Nehe",
    "Birmingham",
    "Zunhua",
    "Valenzuela",
    "Or?m?yeh",
    "Wugang",
    "Osogbo",
    "Shuangqiao",
    "Comodoro Rivadavia",
    "Cagayan de Oro",
    "Langzhong",
    "Qian’an",
    "Lviv",
    "Zouping",
    "An Najaf",
    "Sagamihara",
    "Sarasota",
    "Mississauga",
    "Okayama",
    "Anlu",
    "Dayton",
    "Changsha",
    "Torreón",
    "Shihezi",
    "George Town",
    "Enugu",
    "Soledad",
    "Jaboatão",
    "Yanggok",
    "Yatou",
    "Santo André",
    "Xichang",
    "Bhiwandi",
    "City of Parañaque",
    "Dasmariñas",
    "Chengxiang",
    "Sah?ranpur",
    "Warangal",
    "Edogawa",
    "Osasco",
    "Dashiqiao",
    "Latakia",
    "Rochester",
    "Fresno",
    "Banjarmasin",
    "Salem",
    "General Santos",
    "?am?h",
    "Bacoor",
    "Shishi",
    "Guadalupe",
    "Adachi",
    "Qianxi",
    "Tolyatti",
    "Macau",
    "Bauchi",
    "Hamilton",
    "?ód?",
    "Miluo Chengguanzhen",
    "Gaizhou",
    "M?legaon",
    "Karbal?’",
    "Leling",
    "São José dos Campos",
    "Sevilla",
    "Jianshe",
    "Shizuoka",
    "Jingcheng",
    "Kochi",
    "Allentown",
    "Tasikmalaya",
    "Rasht",
    "Xinmin",
    "Zhongshu",
    "Xigazê",
    "Gorakhpur",
    "As Sulaym?n?yah",
    "Zaragoza",
    "Acapulco de Juárez",
    "Bah?r",
    "Palermo",
    "Guankou",
    "Tulsa",
    "Tlaquepaque",
    "Mazatlán",
    "Songyang",
    "Cape Coral",
    "Ch’?ngjin",
    "Puyang Chengguanzhen",
    "Qionghu",
    "Ribeirão Prêto",
    "Zhaodong",
    "Huambo",
    "Wenchang",
    "Shulan",
    "Tlalnepantla",
    "Catia La Mar",
    "Sargodha",
    "Al Huf?f",
    "Durango",
    "Jalingo",
    "Bouaké",
    "Sialkot City",
    "San Jose del Monte",
    "Ansan",
    "Lingbao Chengguanzhen",
    "Hwasu-dong",
    "Hu?",
    "Shimoga",
    "Bulawayo",
    "Xiping",
    "Sanhe",
    "Gunt?r",
    "Concord",
    "Contagem",
    "Tirupp?r",
    "Ch’?nan",
    "Tripoli",
    "Honch?",
    "Düsseldorf",
    "Izhevsk",
    "Guixi",
    "Sorocaba",
    "Petaling Jaya",
    "Tengyue",
    "Wuxue",
    "Kikwit",
    "Colorado Springs",
    "Qufu",
    "Gaobeidian",
    "Ruiming",
    "Wroc?aw",
    "Gold Coast",
    "Xinshi",
    "Ta‘izz",
    "Aracaju",
    "Cochabamba",
    "Jeonju",
    "Jin’e",
    "Barnaul",
    "Makati City",
    "Stuttgart",
    "Rotterdam",
    "Changping",
    "Benghazi",
    "Kryvyi Rih",
    "Raurkela",
    "?alw?n",
    "Charleston",
    "Chimalhuacán",
    "Xinxing",
    "Suohe",
    "Mangalore",
    "Zhuangyuan",
    "Glasgow",
    "Namangan",
    "Ulyanovsk",
    "Irkutsk",
    "N?nded",
    "Jos",
    "Pontianak",
    "Villa Nueva",
    "Bazhou",
    "Springfield",
    "Turpan",
    "Las Piñas City",
    "Meihekou",
    "Jurong",
    "Feira de Santana",
    "Khabarovsk",
    "Xinji",
    "Serang",
    "Kandah?r",
    "Sanya",
    "San Miguel de Tucumán",
    "Yaroslavl",
    "Zhangshu",
    "Ba?c?lar",
    "Grand Rapids",
    "Vladivostok",
    "Kuantan",
    "Gothenburg",
    "Cuttack",
    "Jambi",
    "Cimahi",
    "Bacolod",
    "Zhuozhou",
    "Uberlândia",
    "Tianchang",
    "Kawaguchi",
    "Itabashi",
    "Suginami-ku",
    "Tuxtla",
    "Tumk?r",
    "Leipzig",
    "Balikpapan",
    "Qamdo",
    "Durban",
    "Ch?nda",
    "Kagoshima",
    "Al ?illah",
    "Makhachkala",
    "Sihui",
    "Mar del Plata",
    "Irapuato",
    "Brampton",
    "Luocheng",
    "Pereira",
    "Mission Viejo",
    "Dortmund",
    "Reynosa",
    "Chuxiong",
    "Z?hed?n",
    "Jinhua",
    "Albany",
    "Shah Alam",
    "Knoxville",
    "Cuiabá",
    "Shangzhi",
    "Essen",
    "Botou",
    "Bucaramanga",
    "Anyang",
    "Genoa",
    "Port Sudan",
    "Puente Alto",
    "Dehra D?n",
    "A? ??’if",
    "Bakersfield",
    "Wancheng",
    "Málaga",
    "Hachi?ji",
    "Ogden",
    "Xiulin",
    "Fu’an",
    "Tomsk",
    "Tonalá",
    "Kumul",
    "Bristol",
    "Luofeng",
    "Lingyuan",
    "Irbid",
    "Baton Rouge",
    "Huzhou",
    "Wencheng",
    "Bremen",
    "Ciudad Bolívar",
    "Durg?pur",
    "Orenburg",
    "Shenzhou",
    "?sansol",
    "Akron",
    "Kuiju",
    "New Haven",
    "Zhenzhou",
    "Surakarta",
    "Jieshou",
    "Benguela",
    "Ensenada",
    "Dangyang",
    "Columbia",
    "Kemerovo",
    "Her?t",
    "Dresden",
    "Bh?vnagar",
    "Juiz de Fora",
    "Luanzhou",
    "Hamad?n",
    "Novokuznetsk",
    "Nellore",
    "Chiclayo",
    "Manchester",
    "Al ?udaydah",
    "Amr?vati",
    "Cabinda",
    "Korla",
    "Huanghua",
    "Muntinlupa City",
    "Londrina",
    "Tab?k",
    "Heroica Matamoros",
    "Samarkand",
    "Xingcheng",
    "Kaiyuan",
    "Hannover",
    "Valledupar",
    "Fengcheng",
    "Ajmer",
    "Ghulja",
    "Tinnevelly",
    "City of Calamba",
    "Xiangyang",
    "Fuding",
    "An N??ir?yah",
    "Al ?illah",
    "Ibagué",
    "Ryazan",
    "Kassala",
    "Chang’an",
    "Kerm?n",
    "K?t?-ku",
    "Pozna?",
    "Aksu",
    "Salta",
    "Astrakhan",
    "Wuhai",
    "Mingguang",
    "Naberezhnyye Chelny",
    "Antwerp",
    "Touba",
    "Ardab?l",
    "B?kaner",
    "Lyon",
    "Agartala",
    "Ndola",
    "Himeji",
    "Tultitlán de Mariano Escobedo",
    "Villavicencio",
    "Ailan Mubage",
    "Bandar ‘Abb?s",
    "B?c Ninh",
    "Ciudad Apodaca",
    "Santa Teresa del Tuy",
    "Maipú",
    "Penza",
    "Soacha",
    "Port Said",
    "Yucheng",
    "Meknès",
    "Ar?k",
    "Pohang",
    "Longzhou",
    "Anda",
    "Jinghong",
    "Sheffield",
    "Utsunomiya",
    "Suez",
    "Nuremberg",
    "Liverpool",
    "Mesa",
    "Surrey",
    "Heshan",
    "Zhoushan",
    "Ujjain",
    "Jiaji",
    "Santa Marta",
    "Joinvile",
    "Beining",
    "H?i D??ng",
    "Carrefour",
    "Maturín",
    "Homyel’",
    "Ananindeua",
    "Yanji",
    "Yicheng",
    "Ulh?snagar",
    "Lipetsk",
    "Al ‘Am?rah",
    "Choloma",
    "Sevastopol",
    "Encheng",
    "Aden",
    "Kitwe",
    "Matsuyama",
    "Jh?nsi",
    "Kashgar",
    "Palm Bay",
    "Pingtung",
    "Lapu-Lapu City",
    "Montería",
    "Ichikawa",
    "Imus",
    "Davangere",
    "Jammu",
    "Yiwu",
    "Belas",
    "Talatona",
    "Ile-Ife",
    "Kirov",
    "Jiaxing",
    "Mykolaiv",
    "Provo",
    "Meicheng",
    "Niterói",
    "Matsudo",
    "Sukkur",
    "Oujda-Angad",
    "Taozhou",
    "Higashi-?saka",
    "Johor Bahru",
    "Worcester",
    "Hongjiang",
    "Chimbote",
    "Duisburg",
    "Qaraghandy",
    "Ixtapaluca",
    "Dengtacun",
    "Zhijiang",
    "Chengjiao",
    "Beipiao",
    "Suoluntun",
    "Murrieta",
    "Kota Bharu",
    "Ciudad López Mateos",
    "Celaya",
    "Vinh",
    "Duyun",
    "Los Mochis",
    "Nyala",
    "Larkana",
    "Nishinomiya-hama",
    "‘Ajm?n",
    "Cheboksary",
    "Yuanping",
    "Toulouse",
    "Edinburgh",
    "Belgaum",
    "Tula",
    "Shahe",
    "Serra",
    "Gaoping",
    "Greenville",
    "Gulbarga",
    "Dunhua",
    "Brookhaven",
    "Az Zarq?’",
    "Sylhet",
    "Wichita",
    "Toledo",
    "Kaihua",
    "J?mnagar",
    "Fuyuan",
    "Dh?lia",
    "Gaya",
    "Florianópolis",
    "Chiniot",
    "Jiannan",
    "?ita",
    "Kaliningrad",
    "Nangong",
    "Kurashiki",
    "Staten Island",
    "Küçükçekmece",
    "San Juan",
    "Vila Velha",
    "Maz?r-e Shar?f",
    "Macapá",
    "Shekhupura",
    "Des Moines",
    "Piura",
    "Mandaluyong City",
    "Jiaojiangcun",
    "Laohekou",
    "Kâ??thane",
    "Angeles City",
    "Pasay City",
    "Beian",
    "Fujin",
    "Leicester",
    "Xiaoyi",
    "Lanús",
    "Qingzhen",
    "Ba‘q?bah",
    "Katsushika-ku",
    "Buraydah",
    "Gda?sk",
    "Marikina City",
    "Manado",
    "Campos",
    "Calabar",
    "Kanazawa",
    "Iloilo",
    "Long Beach",
    "Kuqa",
    "Jalgaon",
    "Cranbourne",
    "Port St. Lucie",
    "Murcia",
    "Mauá",
    "Fukuyama",
    "Tel Aviv-Yafo",
    "Xicheng",
    "Amagasaki",
    "Pyeongtaek",
    "Kurnool",
    "Denton",
    "Melaka",
    "Taoyuan District",
    "General Trias",
    "Jian’ou",
    "Huadian",
    "?an??",
    "Kota Kinabalu",
    "Minzhu",
    "Bukavu",
    "R?jsh?hi",
    "Balashikha",
    "Udaipur",
    "Kursk",
    "Mariupol",
    "Esl?mshahr",
    "San Nicolás de los Garza",
    "Hsinchu",
    "Barcelona",
    "Constantine",
    "Tanbei",
    "Ado-Ekiti",
    "Madison",
    "Bellary",
    "Rodriguez",
    "Santiago de Cuba",
    "Yongji",
    "Reno",
    "Danjiangkou",
    "São José do Rio Prêto",
    "Fujisawa",
    "Andijon",
    "Harrisburg",
    "Machida",
    "Ning’an",
    "Little Rock",
    "Zhangjiakou Shi Xuanhua Qu",
    "Zürich",
    "Sunch’?n",
    "Jinchang",
    "Kashiwa",
    "Guangming",
    "S?ngli",
    "Tuticorin",
    "Beira",
    "Kupang",
    "Jeju",
    "Caxias do Sul",
    "Santos",
    "Manizales",
    "Stavropol",
    "Yogyakarta",
    "Calicut",
    "Veracruz",
    "Zanj?n",
    "Cusco",
    "Welkom",
    "Ulan-Ude",
    "Oakland",
    "Shinagawa-ku",
    "K?sh?n",
    "Kenitra",
    "Uyo",
    "Sokoto",
    "Masan",
    "Sidi Bouzid",
    "Porto Velho",
    "Sih?ng",
    "Xalapa",
    "Florencio Varela",
    "Uijeongbu",
    "Akola",
    "Aomori",
    "Yan’an Beilu",
    "Agadir",
    "Mogi das Cruzes",
    "Durham",
    "Diadema",
    "Likasi",
    "Buenaventura",
    "Yazd",
    "Laval",
    "Toyota",
    "Santa Rosa",
    "Winston-Salem",
    "Tver",
    "Elaz??",
    "Hpa-An",
    "Palma",
    "Bonita Springs",
    "Mishan",
    "Hailin",
    "Seremban",
    "Lecheng",
    "Zhengjiatun",
    "Luhansk",
    "Pencheng",
    "Magnitogorsk",
    "Takamatsu",
    "El Obeid",
    "Dalai",
    "Xingren",
    "Kolwezi",
    "Wenlan",
    "Indio",
    "Palm Coast",
    "Biñan",
    "Arusha",
    "Fenyang",
    "Paju",
    "Mataram",
    "Chattanooga",
    "Kisumu",
    "Jhang City",
    "Nagqu",
    "Jayapura",
    "Rio Branco",
    "Toyama",
    "Fangting",
    "Sanandaj",
    "Linghai",
    "Toyonaka",
    "Spokane",
    "Sochi",
    "Bh?galpur",
    "Ivanovo",
    "Türkmenabat",
    "Zaria",
    "Bryansk",
    "Asy??",
    "Taiping",
    "Mbale",
    "Maracay",
    "Jiexiu",
    "Santa Fe",
    "Campina Grande",
    "Nagasaki",
    "Szczecin",
    "Syracuse",
    "Maringá",
    "Carapicuíba",
    "Qazv?n",
    "Quilon",
    "Jundiaí",
    "Hirakata",
    "Gifu",
    "Lancaster",
    "S?kar",
    "Jiangjiafan",
    "Dera Ghazi Khan",
    "Mwanza",
    "Arlington",
    "Xushan",
    "Miyazaki",
    "Yuyao",
    "Stockton",
    "Bh?tp?ra",
    "Sandakan",
    "Taytay",
    "Hejin",
    "Thanh Hóa",
    "Minamisuita",
    "Poughkeepsie",
    "Yokosuka",
    "Nha Trang",
    "Belgorod",
    "Malabon",
    "Yola",
    "Lobito",
    "Saurimo",
    "Olinda",
    "Esenler",
    "Gujrat",
    "Ad D?w?n?yah",
    "Piracicaba",
    "Hancheng",
    "Karamay",
    "K?kin?da",
    "Augusta",
    "Bh?lw?ra",
    "Tieli",
    "Cilegon",
    "Niz?m?b?d",
    "Bologna",
    "Boise",
    "Esenyurt",
    "Tétouan",
    "Aqtöbe",
    "Oxnard",
    "Oyo",
    "Tarlac City",
    "Okazaki",
    "Cainta",
    "??’il",
    "Yidu",
    "Lianzhou",
    "Florence",
    "Christchurch",
    "Nuevo Laredo",
    "Scranton",
    "Brno",
    "London",
    "Novi Sad",
    "Gusau",
    "Modesto",
    "Pasto",
    "Kissimmee",
    "Las Palmas",
    "Ichinomiya",
    "P?nih?ti",
    "Huancayo",
    "Aurora",
    "Betim",
    "Sintra",
    "Parbhani",
    "Usulután",
    "Youngstown",
    "Iquitos",
    "Helixi",
    "Manukau City",
    "Cumaná",
    "Rohtak",
    "Vinnytsia",
    "L?t?r",
    "Lipa City",
    "Mandaue City",
    "Bello",
    "Khorram?b?d",
    "Ambon",
    "Butuan",
    "Keelung",
    "Toyohashi",
    "Baguio City",
    "La Florida",
    "Lengshuijiang",
    "Anguo",
    "Kita-ku",
    "R?jap?laiyam",
    "Panshi",
    "Madan",
    "Plovdiv",
    "Az Zubayr",
    "Al Qa??f",
    "Takasaki",
    "Huichang",
    "Vitsyebsk",
    "Nagano",
    "Bauru",
    "Yanjiao",
    "Bochum",
    "Tecámac",
    "Anápolis",
    "Coventry",
    "Shinjuku",
    "W?nsan",
    "Caerdydd",
    "Iligan",
    "Cabuyao",
    "Nakano",
    "Bengkulu",
    "Orizaba",
    "Blumenau",
    "Montes Claros",
    "Pétion-Ville",
    "Shuanghejiedao",
    "Umuahia",
    "Surgut",
    "Gedaref",
    "Palu",
    "Pokhara",
    "Mahilyow",
    "Wudalianchi",
    "Sungai Petani",
    "Nam ??nh",
    "Vitória",
    "Hrodna",
    "Vladimir",
    "São Vicente",
    "Taraz",
    "Cubal",
    "Kawagoe",
    "Ibb",
    "Yong’an",
    "Wuppertal",
    "Manisa",
    "San Fernando",
    "Minatitlán",
    "Nizhniy Tagil",
    "San Pedro",
    "Hongzhai",
    "Wakayama",
    "Bilbao",
    "Rahimyar Khan",
    "Pavlodar",
    "Gimpo",
    "Itaquaquecetuba",
    "Nara",
    "Van",
    "Corrientes",
    "Neiva",
    "Arkhangelsk",
    "Batangas",
    "Licheng",
    "Koshigaya",
    "Sin?iju",
    "Cabimas",
    "Yueqing",
    "Yakeshi",
    "Ahmadnagar",
    "Fayetteville",
    "Takatsuki",
    "Holguín",
    "Qoqon",
    "Anaheim",
    "Semey",
    "Varna",
    "Yingmen",
    "Cariacica",
    "Palmira",
    "Tapachula",
    "Konak",
    "Bydgoszcz",
    "Hatay",
    "Antofagasta",
    "R?jahmundry",
    "Chita",
    "Chitungwiza",
    "Caruaru",
    "Utrecht",
    "Pensacola",
    "Victorville",
    "Tanch’?n",
    "Tokorozawa",
    "Nice",
    "Sumqay?t",
    "K?st?",
    "Cuddapah",
    "Simferopol",
    "?tsu",
    "Vitória da Conquista",
    "Lancaster",
    "Makiivka",
    "East London",
    "Greensboro",
    "Uruapan",
    "Gómez Palacio",
    "Franca",
    "Brest",
    "Kaluga",
    "Corpus Christi",
    "Muzaffarpur",
    "Yeosu",
    "Lublin",
    "Alwar",
    "Brahmapur",
    "Lianran",
    "Buôn Ma Thu?t",
    "Cuernavaca",
    "Beni",
    "Randburg",
    "Alicante",
    "Jitpur",
    "Kaes?ng",
    "Petrolina",
    "Chinju",
    "Tangdong",
    "Hangu",
    "Belfast",
    "Iwaki",
    "Blida",
    "Salamanca",
    "Yingzhong",
    "Hirosaki",
    "Viña del Mar",
    "Nazr?t",
    "Bielefeld",
    "Cuenca",
    "Al Fayy?m",
    "Fort Wayne",
    "Ciudad Obregón",
    "Wad Medani",
    "Ribeirão das Neves",
    "Soledad de Graciano Sánchez",
    "Bonn",
    "K?m?rh?ti",
    "Maebashi",
    "Thessaloníki",
    "G?nc?",
    "Mymensingh",
    "Santa Ana",
    "Flint",
    "Kendari",
    "Thái Nguyên",
    "Smolensk",
    "Asahikawa",
    "Islip",
    "Dah?k",
    "W?nju",
    "Mathura",
    "Nakuru",
    "Lafia",
    "Koriyama",
    "Bamiantong",
    "Pati?la",
    "Taourirt",
    "?zmir",
    "V?ng Tàu",
    "Cabanatuan City",
    "Markham",
    "Saugor",
    "Pelotas",
    "Roodepoort",
    "Volzhskiy",
    "Bij?pur",
    "Sukabumi",
    "Fayetteville",
    "Ulanhot",
    "Yunzhong",
    "Cotabato",
    "Al Fall?jah",
    "K?chi",
    "Minna",
    "Boa Vista",
    "Cluj-Napoca",
    "Canoas",
    "Gwangmyeongni",
    "Bari",
    "Pucallpa",
    "Y?ld?r?m",
    "Kuching",
    "Tepic",
    "Caucaia",
    "Gonder",
    "Uberaba",
    "Jackson",
    "Mekele",
    "Santa Rosa",
    "Gonaïves",
    "Guasave",
    "Lansing",
    "Naha",
    "Binxian",
    "San Juan",
    "Lexington",
    "Hotan",
    "Dongyang",
    "Ciudad del Este",
    "Kaiyuan",
    "Temara",
    "Uíge",
    "Córdoba",
    "Camagüey",
    "Ann Arbor",
    "San Salvador de Jujuy",
    "Timi?oara",
    "Al K?t",
    "Sh?hj?npur",
    "Cherepovets",
    "San Miguelito",
    "Menongue",
    "J?n?gadh",
    "Katsina",
    "Henderson",
    "Poltava",
    "Maroua",
    "Kaech’?n",
    "Asan",
    "Tehuacán",
    "Coatzacoalcos",
    "Nukus",
    "Huntsville",
    "Öskemen",
    "Nantes",
    "Zalantun",
    "Trich?r",
    "Binangonan",
    "Cirebon",
    "Münster",
    "Az Zaq?z?q",
    "Boaco",
    "Cà Mau",
    "Toshima",
    "Vologda",
    "Saransk",
    "Mobile",
    "Barddham?n",
    "Tanza",
    "Bor",
    "Kasur",
    "Yakou",
    "Orël",
    "Shahr-e Qods",
    "Safi",
    "Güngören",
    "Guarujá",
    "Playa del Carmen",
    "Purnea",
    "Datang",
    "Zarzal",
    "Fort Collins",
    "Port Elizabeth",
    "Asheville",
    "Santa Clarita",
    "Gorg?n",
    "Quy Nh?n",
    "Sambalpur",
    "Mannheim",
    "Yakutsk",
    "Yokkaichi",
    "Ponta Grossa",
    "Catania",
    "Chalco",
    "Karlsruhe",
    "Shahr??r",
    "Kurgan",
    "Kasugai",
    "Sariw?n",
    "St. Catharines",
    "Matadi",
    "Niagara Falls",
    "F?roz?b?d",
    "St. Paul",
    "Vladikavkaz",
    "Hisar",
    "Puerto La Cruz",
    "Puerto Princesa",
    "Podolsk",
    "Meguro",
    "Ciudad Victoria",
    "Ciudad Santa Catarina",
    "Vaughan",
    "?wasa",
    "?akashich?",
    "Pekalongan",
    "Kurume",
    "Vila Nova de Gaia",
    "Curepipe",
    "Paulista",
    "Oaxaca",
    "Armenia",
    "Akita",
    "Awka",
    "San Bernardo",
    "Iksan",
    "Taubaté",
    "Antioch",
    "Lakeland",
  ];



  // Demo list to show querying


  // first overwrite to
  // clear the search text
  @override
  List<Widget>? buildActions(BuildContext context) {

    return [
      IconButton(
        onPressed: () {
          query = '';
        },
        icon: const Icon(Icons.clear),
      ),
    ];
  }

  // second overwrite to pop out of search menu
  @override
  Widget? buildLeading(BuildContext context) {
    return IconButton(
      onPressed: () {
        close(context, null);
      },
      icon: const Icon(Icons.arrow_back),
    );
  }

  // third overwrite to show query result
  @override
  Widget buildResults(BuildContext context) {
    List<String> matchQuery = [];
    for (var fruit in searchTerms) {
      if (fruit.toLowerCase().contains(query.toLowerCase())) {
        matchQuery.add(fruit);
      }
    }
    return ListView.builder(
      itemCount: matchQuery.length,
      itemBuilder: (context, index) {
        var result = matchQuery[index];
        return ListTile(
          title: Text(result),
        );
      },
    );
  }

  // last overwrite to show the
  // querying process at the runtime
  @override
  Widget buildSuggestions(BuildContext context) {
    List<String> matchQuery = [];
    for (var fruit in searchTerms) {
      if (fruit.toLowerCase().contains(query.toLowerCase())) {
        matchQuery.add(fruit);
      }
    }
    return ListView.builder(
      itemCount: matchQuery.length,
      itemBuilder: (context, index) {
        var result = matchQuery[index];
        return ListTile(
          title: Text(result),
        );
      },
    );
  }
}